### PR TITLE
Added GOTV CVARs

### PR DESCRIPTION
**Pull request by FlowingSPDG**
Hello, I'm using this image for my development
Could you add GOTV related cvars for server? I can add more cvars if needed
Thanks

### CODE REVIEW

**Comment by Apfelwurm** [comment]
Ty @FlowingSPDG ! ofc, i'll merge this one, but will take until tomorrow to actually build and push it with the features, since i also have to find a better solution for the automatic docker hub update.

**Comment by FlowingSPDG** [comment]
Cool cool! Thanks you!

**Comment by Apfelwurm** [comment]
currently the image is pushing, but it seems that its going to take around 1-1.5h until its up.
If you want to add more features, it would be great to PR them together, since the rebuild takes a lot of time to build and expecially push :D Sadly the gh runners have not enough space to do that in the ci, so i have to do it on my local machine (40Mbit/s upload). ntl, i appreciate any contributions, but it maybe takes a few days until i can merge and push stuff :)

**Comment by FlowingSPDG** [comment]
Oh okay! I was thinking to add 128tick settings(sv_mincmdrate or smt, sv_minupraterate?) and few more stuffs so I'll put them together when I send PR!

**Pull request merged**
